/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ina' at '17.11.16 13:23' with Gradle 3.1
 *
 * @author Ina, @date 17.11.16 13:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
